Adds verbose docs and example .env
intelagense/yallarehere pull request #6
Opened 2023-08-17 22:51 UTC by intelagense

## Changes
- Provides a simple contributing guide and fills out the README.md
- Provides .env.local.example for contributors to study

2023-08-21 18:22 UTC, Caleb-Cohen requested changes

2023-08-21 18:22 UTC, Caleb-Cohen commented on .env.local.example
> +DB_STRING = 'mongodb+srv://[username]:[password]@[cluster].mongodb.net/'
I believe there's edge cases where you'll run into potential issues with a space between the `=` with `.ENV` variables.

I'd consider changing this to 

`DB_STRING='mongodb+srv://[username]:[password]@[cluster].mongodb.net/'

Also, I recommend adding a new line.

2023-08-21 18:22 UTC, Caleb-Cohen commented on README.md
> +    DB_STRING = 'mongodb+srv://<username>:<password>@<cluster>.mongodb.net/'
same comment.

2023-08-25 17:39 UTC, KhuloodHassan approved these changes

2023-08-25 18:17 UTC, merged